/**
 * Mock data for testing warehouse functionality
 */

export const mockWarehouse = {
  id: 1,
  warehouseOwnerType: 'Owner',
  warehouseType: 'Industrial',
  address: '123 Test Street',
  googleLocation: 'https://maps.google.com/test',
  city: 'Test City',
  state: 'Test State',
  postalCode: '123456',
  zone: 'North',
  contactPerson: 'John Doe',
  contactNumber: '1234567890',
  totalSpaceSqft: [10000, 5000],
  offeredSpaceSqft: '8000',
  numberOfDocks: '5',
  clearHeightFt: '25',
  compliances: 'Fire Safety, Environmental',
  otherSpecifications: 'Temperature controlled',
  ratePerSqft: '50',
  availability: 'Available',
  uploadedBy: 'test@example.com',
  visibility: true,
  isBroker: 'No',
  photos: 'https://example.com/photo1.jpg,https://example.com/photo2.jpg',
  WarehouseData: {
    latitude: 12.9716,
    longitude: 77.5946,
    fireNocAvailable: true,
    fireSafetyMeasures: 'Sprinklers, Fire Extinguishers',
    landType: 'Commercial',
    approachRoadWidth: '40',
    dimensions: '100x200',
    parkingDockingSpace: 'Ample parking for 50 vehicles',
    pollutionZone: 'Green',
    powerKva: '500',
    vaastuCompliance: true,
  },
};

export const mockWarehouses = [
  mockWarehouse,
  {
    id: 2,
    warehouseOwnerType: 'Tenant',
    warehouseType: 'Cold Storage',
    address: '456 Storage Ave',
    googleLocation: 'https://maps.google.com/test2',
    city: 'Storage City',
    state: 'Storage State',
    postalCode: '654321',
    zone: 'South',
    contactPerson: 'Jane Smith',
    contactNumber: '9876543210',
    totalSpaceSqft: [15000],
    offeredSpaceSqft: '12000',
    numberOfDocks: '8',
    clearHeightFt: '30',
    compliances: 'Cold Storage Compliance',
    otherSpecifications: 'Refrigerated units',
    ratePerSqft: '75',
    availability: 'Occupied',
    uploadedBy: 'admin@example.com',
    visibility: true,
    isBroker: 'Yes',
    photos: 'https://example.com/photo3.jpg',
    WarehouseData: {
      latitude: 13.0827,
      longitude: 80.2707,
      fireNocAvailable: false,
      fireSafetyMeasures: 'Fire Alarms',
      landType: 'Industrial',
      approachRoadWidth: '50',
      dimensions: '150x250',
      parkingDockingSpace: 'Parking for 100 vehicles',
      pollutionZone: 'Orange',
      powerKva: '1000',
      vaastuCompliance: false,
    },
  },
];

export const mockWarehouseFormData = {
  warehouseOwnerType: 'Owner',
  warehouseType: 'Distribution Center',
  address: '789 Distribution Blvd',
  googleLocation: 'https://maps.google.com/test3',
  city: 'Distribution City',
  state: 'Distribution State',
  postalCode: '789012',
  zone: 'East',
  contactPerson: 'Bob Johnson',
  contactNumber: '5551234567',
  totalSpaceSqft: [20000],
  offeredSpaceSqft: '18000',
  numberOfDocks: '10',
  clearHeightFt: '35',
  compliances: 'All Standard Compliances',
  otherSpecifications: 'Modern facility',
  ratePerSqft: '60',
  availability: 'Available',
  uploadedBy: 'user@example.com',
  visibility: true,
  isBroker: 'No',
  photos: null,
  warehouseData: {
    latitude: 19.076,
    longitude: 72.8777,
    fireNocAvailable: true,
    fireSafetyMeasures: 'Complete fire safety system',
    landType: 'Commercial',
    approachRoadWidth: '45',
    dimensions: '200x300',
    parkingDockingSpace: 'Large parking area',
    pollutionZone: 'Green',
    powerKva: '750',
    vaastuCompliance: 'true',
  },
};

export const mockApiErrors = {
  validation: {
    error: 'Validation failed',
    issues: [
      { path: ['warehouseType'], message: 'Warehouse type is required' },
      { path: ['contactNumber'], message: 'Invalid phone number format' },
    ],
  },
  notFound: {
    error: 'Warehouse not found',
  },
  serverError: {
    error: 'Internal server error',
  },
  networkError: {
    message: 'Network error - please check your connection and try again',
  },
};
